manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: chance                         #new entry
      url-base: https://github.com/teenageninja637-ai  #new entry
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 0.3
      import: app/west.yml
    - name: zmkTest05  #new entry
      remote: chance                       #new entry
      revision: main                      #new entry
  self:
    path: config
